services:
  bash:
    runtime: nvidia
    image: cybersatori/image-gpt
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # for X-forwarding
      - /tmp:/tmp
      - .:/root
    environment:
      - DISPLAY=$DISPLAY
    entrypoint: /bin/bash
    working_dir: /root
#    user: "7610:1040" # uid:groupid, can't be automated because docker-compose can't run bash commands (so i'll do something like $(id -u):$(id -g)
